### ISSUE TITLE
Change groupId

### ISSUE THREAD

**Issue by SOF3** [lamba92/kotlin-extlib#12]
Since this repo is no longer under @lamba92's personal account, it might be appropriate to change the groupId to something other than `comgithub.lamba92`.

**Comment by lamba92** [comment]
Yes, I was looking for a DNS record available but the ones following the repository name are already taken.
•  extra.org is taken so kotlin.extra.org is taken as well.
•  kotlin.org is taken so extra.kotlin.org is taken as well.

I was thinking something kotliextra.org so that the namespace will be org.kotlinextra , but I do not like it very much. Any ideas?

**Comment by altavir** [comment]
Nobody forces the package to represent actual domain. In fact it almost never works this way. The library is currently not in the state to have it's own site and domain, just use the github pages instead.

**Comment by lamba92** [comment]
Afaik on the central repository they ask if you own your domain and to prove that by adding a TXT record with custom text during the creation of your namespace on the SonaType issue center.
I was willing to publish this library under `it.lamba` at the beginning but they asked me if I owned the domain or not, so I rolled back to `com.github.lamba92`

**Comment by lamba92** [comment]
I bought for few dollars `kotlinextra.org` and enabled `org.kotlinextra` domain on Maven Central. As soon as I'll be back at home this Tuesday I'll publish them and update the readme
