### ISSUE TITLE
Merge with KrazyKotlin

### ISSUE THREAD

**Issue by dirkbolte** [lamba92/kotlin-extlib#16]
I'm currently looking for a generic Kotlin extension library to use and to contribute some scope-specific extensions to. Next to this I was stumbling across https://github.com/vanshg/KrazyKotlin .

@vanshg I wonder whether the efforts of both projects can be merged.

**Comment by lamba92** [comment]
Unfortunately lately I've been very busy with university and work. I had no time to update this repo but I'm willing to in the future. 

The aim of `kotlin-extlib` is to reimplement some nice classes we are used to in JVM in Kotlin multiplatform so that they are available everywhere. KrazyKotlin seems to have a different goal, I it would not be a good idea to merge everything together.
